PROJECTNAME: PIDNetS_FIRE_REGION_W005_RGB_FLAME2
SESSIONAME: training_only_fire_region_w005
EXPERIMENT_GROUP: pidnet_s_fire_region
DEVICE: cuda:0
NUM_WORKERS: 0
SEED: 200

MODEL: pidnet_s
TRAINING_OBJECTIVE: fire_region
NUM_OUTPUTS: 2
PRETRAINED: G:/py2/weights/PIDNet_S_ImageNet.pth.tar
CHECKPOINT: null

ROOTDATASET: G:/py2/data
TRAINSET: lists/train_flm.txt
VALIDSET: lists/val_flm.txt
TESTSET: lists/test_flm.txt
NUM_CLASSES: 3
CLS_NAMES:
  - background
  - smoke
  - fire
MODE: rgb
MULTISCALE: true
FLIP: true
BRIGHTNESS: true
SINGLE_SOURCE: false
COMP_MASK: false
BLEND_IMGS: false
IGNORE_LABEL: 255
SCALE_FACTOR: 10
CROP_SIZE:
  - 256
  - 256
BASE_SIZE: 256

CLASS_WEIGHTS:
  - 2.27681343
  - 3.04257527
  - 8.8657764
ALIGN_CORNERS: true

LR: 0.001
BATCHSIZE: 4
EPOCHS: 10
LR_TOTAL_EPOCHS: 100
OPTIM: SGD
SCHED: POLY
USE_OHEM: false
OHEMTHRES: 0.9
OHEMKEEP: 131072
WD: 0.00001
MOMENTUM: 0.9
BALANCE_WEIGHTS:
  - 0.4
  - 1.0
T_THRESH_BDLOSS: 0.8
BD_WEIGHT: 1.0
SB_WEIGHTS: 1.0

FIRE_CLASS_INDEX: 2
FIRE_REGION_WEIGHT: 0.05
FIRE_FOCAL_ALPHA: 0.75
FIRE_FOCAL_GAMMA: 2.0
FIRE_FOCAL_WEIGHT: 1.0
FIRE_TVERSKY_ALPHA: 0.3
FIRE_TVERSKY_BETA: 0.7
FIRE_TVERSKY_WEIGHT: 1.0
